### PR TITLE
fix: stub never signalled measurement complete, causing hang

### LINKED ISSUE #39: Multiharp recording does not terminate when stubs are used
When `tdc_toolkit record` is called while using a stub in place of mhlib, recording does not terminate and the output Parquet file is not properly closed and flushed, resulting in an unreadable file.

It is not clear if the problem is in the mhlib stub, the higher-level driver stub, or both, but it should be possible to isolate the problem with testing.

Reproduce with a build that does not include the real mhlib, forcing use of the stub, e.g.:

```
tdc_toolkit record --device-config config.json --duration 1s
```

The progress bar will move to completion and the program will hang, requiring termination with Control-C.

### PR DESCRIPTION
**Pull request by EliottFlechtner**
## Summary

Fixes #39.

When running `tdc_toolkit record` against the stub device (`--device-type mh160-stub-generator` or `--mh-wrapper-implementation stub`), the program would **hang indefinitely** after the requested measurement duration elapsed and **never exit**.

## Root cause

`MhlibWrapperStub` (the stub implementation of the `MhlibWrapper` trait used for testing and for running without real hardware) had three methods that **did not simulate any real behaviour**:

| Method | Old behaviour | Actual device behaviour |
|---|---|---|
| `start_measurement` | No-op | Sets the timer for how long to acquire |
| `stop_measurement` | No-op | Stops the acquisition timer |
| `ctc_status` | Always returned `0` (still running) | Returns non-zero when acquisition time has elapsed |
| `read_fifo` | Always returned `[0u32]` (data present) | Returns empty buffer when no data is available |
| `is_measurement_running` | Always returned `true` | Returns `false` once acquisition time has elapsed |

The recording loop in `MH160Device::do_stream_measurement` polls `ctc_status` and `read_fifo` to decide when to stop. Because the **stub never signalled completion**, the loop ran forever.

## Fix

Added a `measurement_end: Mutex<Option<Instant>>` field to `MhlibWrapperStub` to track when the current measurement should finish:

- `start_measurement` now records `Instant::now() + Duration::from_millis(acquisition_time)` as the end time.
- `stop_measurement` clears the end time back to `None`.
- A new private helper `measurement_is_complete()` checks whether the end time has been reached.
- `ctc_status` now returns `1` (complete) when `measurement_is_complete()` is true, matching the real MHLib convention.
- `read_fifo` now returns an empty buffer when `measurement_is_complete()`, and sleeps 100 ms between calls while the measurement is still running to prevent the polling loop from spinning at full CPU speed and flooding downstream channels.
- `is_measurement_running` now correctly returns `false` once the acquisition time has elapsed.

`PartialEq` and `Clone` are manually implemented so the new `Mutex` field **does not prevent those derives**; `Clone` creates a fresh instance with `measurement_end: None` rather than _copying the lock state_.

## Testing

- `cargo clippy`: clean
- `cargo test`: 22/22 tests pass
- `cargo build --all-features` (with real MHLib installed) — clean
- check.bash: all steps pass

### CODE REVIEW

File: src/multiharp/mhlib_wrapper/stub.rs [hunk 1]
```diff
@@ -1,20 +1,57 @@
...
-#[derive(PartialEq, Clone, Debug)]
+#[derive(Debug)]
 pub struct MhlibWrapperStub {
     device_index: u8,
+    measurement_end: Mutex<Option<Instant>>,
+}
+
+/// A stub implementation of the `MhlibWrapper` trait for testing purposes.
+/// It simulates the behavior of the real MHLib wrapper without requiring
+/// actual hardware interaction.
```
Comment (auspicacious) [inline src/multiharp/mhlib_wrapper/stub.rs]: This documentation needs to be on `pub struct MhlibWrapperStub`, not here.

File: src/multiharp/mhlib_wrapper/stub.rs [hunk 2]
```diff
@@ -1,20 +1,57 @@
...
+impl PartialEq for MhlibWrapperStub {
+    fn eq(&self, other: &Self) -> bool {
+        self.device_index == other.device_index
+    }
+}
```
Comment (auspicacious) [inline src/multiharp/mhlib_wrapper/stub.rs]: I would say that those two are _not_ equal, given that their state is not the same -- do we really need `PartialEq` for this struct?

File: src/multiharp/mhlib_wrapper/stub.rs [hunk 3]
```diff
@@ -1,20 +1,57 @@
...
+
+/// The `Clone` implementation allows for creating a new instance of
+/// `MhlibWrapperStub` with the same `device_index`, but with a new
+/// `measurement_end` mutex initialized to `None`.
+impl Clone for MhlibWrapperStub {
+    fn clone(&self) -> Self {
+        Self::new(self.device_index)
+    }
```
Comment (auspicacious) [inline src/multiharp/mhlib_wrapper/stub.rs]: I'm a little concerned that `Clone` and `PartialEq` are in use somewhere in the code for this struct -- I'm not sure why they would be used, but it's possible that if `Clone` is being used it will cause issues now that this struct carries state. It would be good to check what happens if we remove the impls and then, if it is really necessary to use this struct across threads, consider what more we need to do to make this effectively thread-safe -- for instance, wrap the Mutex in an Arc.

File: src/multiharp/mhlib_wrapper/stub.rs [hunk 4]
```diff
@@ -166,16 +203,27 @@ impl MhlibWrapper for MhlibWrapperStub {
...
+        // Sets the measurement end time to the current time plus the acquisition time,
+        // allowing `measurement_is_complete` to return `true` once the acquisition time has elapsed.
+        let end = Instant::now() + Duration::from_millis(acquisition_time.try_into()?);
+        *self.measurement_end.lock().unwrap() = Some(end);
         Ok(())
     }
 
+    /// Signals no measurement is running which frees the lock on the measurement end time
+    /// and allows `measurement_is_complete` to return `false` until a new measurement
+    /// is started and sets a new end time
```
Comment (auspicacious) [inline src/multiharp/mhlib_wrapper/stub.rs]: This is documenting the internal implementation, which isn't really appropriate here.

File: src/multiharp/mhlib_wrapper/stub.rs [hunk 5]
```diff
@@ -166,16 +203,27 @@ impl MhlibWrapper for MhlibWrapperStub {
...
     fn stop_measurement(&self) -> Result<()> {
+        *self.measurement_end.lock().unwrap() = None;
         Ok(())
     }
 
+    /// Mirrors the real MHLib `MH_CTCStatus` return value convention:
+    /// `0` means the acquisition time has not yet elapsed (measurement still running),
+    /// non-zero means the acquisition time has elapsed and the measurement is complete.
```
Comment (auspicacious) [inline src/multiharp/mhlib_wrapper/stub.rs]: Since the goal of this stub is to provide a minimal mocked implementation of the real driver, if we're following the exact behavior of the real driver here, we don't need to document this at all -- if anything, we should add documentation to the trait definition.

Also, according to the manual, it's not "non-zero," it's `1`.

Comment (auspicacious) [inline src/multiharp/mhlib_wrapper/stub.rs]: Formatting notes on comments in general: these are going to be rendered using Markdown, meaning that all three of these lines would get wrapped into a single line. However, wrapping the text in the source code like this means that changing even a single word could cause several lines to change in the diff.

This is why, elsewhere in the code, I have made it a policy not to hard-wrap text. If this text is intended to be a single paragraph, it should be on a single line.

On the other hand, this particular comment would be better represented as a list (although, as per my other comment, this documentation should probably just be deleted):

```
/// Mirrors the real MHLib `MH_CTCStatus` return value convention:
///
/// * `0`: the acquisition time has not yet elapsed (measurement still running)
/// * `1`: the acquisition time has elapsed and the measurement is complete
```

Comment (auspicacious) [inline src/multiharp/mhlib_wrapper/stub.rs]: It's an interesting question: on the real device what happens when you call this method when a measurement is not running, and no measurement has been run since the device was first turned on? The documentation doesn't say.

My guess is that it returns `1`. It would have to return `1` after at least one measurement has been run. Or maybe it returns an error. But I suspect it wouldn't return `0`.

However, if I am reading your code correctly, `measurement_is_complete()` returns `0` in this case. It also returns `0` if `stop_measurement()` is called. I suspect that is not the real device's behavior, although it would need to be empirically tested.

File: src/multiharp/mhlib_wrapper/stub.rs [hunk 6]
```diff
@@ -221,12 +269,24 @@ impl MhlibWrapper for MhlibWrapperStub {
...
+    ///
+    /// Sleeps briefly between calls to simulate the real hardware's FIFO fill rate,
+    /// preventing the polling loop in `do_stream_measurement` from spinning at full
+    /// CPU speed and flooding downstream channels with an unbounded backlog.
     fn read_fifo(&self) -> Result<Vec<u32>> {
-        Ok(vec![0u32])
+        if self.measurement_is_complete() {
+            Ok(vec![])
+        } else {
+            thread::sleep(Duration::from_millis(100)); // Sleep justified in function docstring
```
Comment (auspicacious) [inline src/multiharp/mhlib_wrapper/stub.rs]:
```suggestion
            thread::sleep(Duration::from_millis(100));
```

File: src/multiharp/mhlib_wrapper/stub.rs [hunk 7]
```diff
@@ -221,12 +269,24 @@ impl MhlibWrapper for MhlibWrapperStub {
...
+            Ok(vec![0u32])
+        }
     }
 
     fn is_measurement_running(&self) -> Result<bool> {
```
Comment (auspicacious) [inline src/multiharp/mhlib_wrapper/stub.rs]: It looks like this function is not used anywhere, and it doesn't do anything except map the int we get back from `ctc_status` to a boolean. It would be helpful to simply delete this function from the trait definition and the real/stub implementations as part of this PR to prevent confusion.

File: src/multiharp/mhlib_wrapper/stub.rs [hunk 8]
```diff
@@ -1,20 +1,57 @@
...
+    /// Returns `true` if the acquisition time set by `start_measurement` has elapsed (measurement complete).
+    /// Returns `false` if no measurement has been started or the time has not yet elapsed (keeps the lock on `measurement_end`).
+    fn measurement_is_complete(&self) -> bool {
+        self.measurement_end
+            // Locks the `measurement_end` mutex to safely access the end time. If the lock is poisoned, it panics.
+            .lock()
+            // If `measurement_end` = `None`, no measurement is running => 'false'
+            .unwrap()
+            // If `measurement_end` = `Some(end)`, return whether current time has passed `end`
+            .is_some_and(|end| Instant::now() >= end)
```
Comment (auspicacious) [inline src/multiharp/mhlib_wrapper/stub.rs]:
```suggestion
        self.measurement_end
            .lock()
            .unwrap()
            .is_some_and(|end| Instant::now() >= end)
```

Avoid writing comments that simply describe what the code does -- especially since, in this case, the middle comment is actually positioned on the wrong line and is misleading.

File: src/multiharp/mhlib_wrapper/stub.rs [hunk 9]
```diff
@@ -166,16 +203,27 @@ impl MhlibWrapper for MhlibWrapperStub {
         Ok(())
     }
 
-    fn start_measurement(&self, _acquisition_time: i32) -> Result<()> {
+    fn start_measurement(&self, acquisition_time: i32) -> Result<()> {
+        // Sets the measurement end time to the current time plus the acquisition time,
+        // allowing `measurement_is_complete` to return `true` once the acquisition time has elapsed.
+        let end = Instant::now() + Duration::from_millis(acquisition_time.try_into()?);
+        *self.measurement_end.lock().unwrap() = Some(end);
```
Comment (auspicacious) [inline src/multiharp/mhlib_wrapper/stub.rs:188]: I think this implementation will never be a problem in practice because [on all platforms we are likely to use `Instant` is monotonic](https://doc.rust-lang.org/std/time/struct.Instant.html#monotonicity) and it doesn't really matter very much for our use case anyway, but another way to do this would be to store the start time and use `.elapsed()` or a similar method.

Of course you would then have to store a duration for the experiment's start time and synchronize both of them... maybe forget I mentioned it.

**Review by auspicacious — COMMENTED** [review]
Thank you for making this PR, I'm glad to see that you have been able to grasp what the code does and make contributions so quickly.

Brief summary of comments:

* I don't think this is actually thread-safe; see comments on `Clone`. However, I'm also not sure that it needs to be thread-safe, since we typically dedicate one thread to operating the MultiHarp.
* I'm not sure its behavior is what we want; it might return `0` in some cases when it should return `1`.
* I'm glad to see an effort being made to document code, but please consider that you should let code speak for itself; too many comments can be a distraction when they simply restate what the code does. This also applies to the PR summary.
* There's no reason you would have known about my preference to avoid hard-wrapping of comments (and I wish I could enforce it automatically) but I would prefer it if comments were not hard-wrapped.

File: src/multiharp/mhlib_wrapper/stub.rs (hunk 1 above)
Comment (EliottFlechtner) [reply src/multiharp/mhlib_wrapper/stub.rs]: Done, moved the doc comment to pub struct `MhlibWrapperStub`

File: src/multiharp/mhlib_wrapper/stub.rs (hunk 2 above)
Comment (EliottFlechtner) [reply src/multiharp/mhlib_wrapper/stub.rs]: Done, removed. None of the call sites compare stub instances, so nothing breaks.

File: src/multiharp/mhlib_wrapper/stub.rs (hunk 6 above)
Comment (EliottFlechtner) [reply src/multiharp/mhlib_wrapper/stub.rs]: Done, removed.

File: src/multiharp/mhlib_wrapper/stub.rs (hunk 8 above)
Comment (EliottFlechtner) [reply src/multiharp/mhlib_wrapper/stub.rs]: Done, removed all.

File: src/multiharp/mhlib_wrapper/stub.rs (hunk 3 above)
Comment (EliottFlechtner) [reply src/multiharp/mhlib_wrapper/stub.rs]: Done, removed. I checked the current call sites and they all construct stubs via `MhlibWrapperStub::new()` directly, so there were no Clone/PartialEq usages to update. Since nothing is cloning the stub currently, I didn't make any additional thread-safety changes such as wrapping the mutex in an Arc; if that becomes necessary in a future use case, I agree that would be the right direction.

File: src/multiharp/mhlib_wrapper/stub.rs (hunk 4 above)
Comment (EliottFlechtner) [reply src/multiharp/mhlib_wrapper/stub.rs]: Done, removed.

File: src/multiharp/mhlib_wrapper/stub.rs (hunk 7 above)
Comment (EliottFlechtner) [reply src/multiharp/mhlib_wrapper/stub.rs]: @auspicacious I removed it from the stub implementation, and I also confirmed there are **no call sites for it currently in the codebase**. Since the additional changes would touch the trait definition and the real implementation as well, I wanted to check before broadening the scope of this PR: would you like me to remove `is_measurement_running` from `meta.rs` and `real.rs` here too, or would you prefer that as a separate cleanup PR?

File: src/multiharp/mhlib_wrapper/stub.rs (hunk 5 above)
Comment (EliottFlechtner) [reply src/multiharp/mhlib_wrapper/stub.rs]: Done, I removed the doc comment from the stub. I also fixed the behavior so that when no measurement is active, ctc_status() now returns 1 rather than 0, which is a better match for the semantics you pointed out.

Comment (EliottFlechtner) [reply src/multiharp/mhlib_wrapper/stub.rs]: Agreed. I removed the comment rather than rewriting it, so this no longer introduces any hard-wrapped prose in the source.

Comment (EliottFlechtner) [reply src/multiharp/mhlib_wrapper/stub.rs]: Good catch, and fixed. `measurement_is_complete()` now treats `None` as complete via `.is_none_or(|end| Instant::now() >= end)`, so `ctc_status()` returns 1 when no measurement is active, including after stop_measurement(), instead of incorrectly returning 0.

File: src/multiharp/mhlib_wrapper/stub.rs (hunk 9 above)
Comment (EliottFlechtner) [reply src/multiharp/mhlib_wrapper/stub.rs:188]: Fixed. Removed the explanatory comment here, but left the implementation as-is. I agree that using `Instant` directly is fine for this stub and keeps the state minimal.

File: src/multiharp/mhlib_wrapper/stub.rs (hunk 7 above)
Comment (auspicacious) [reply src/multiharp/mhlib_wrapper/stub.rs]: @EliottFlechtner Just do it here unless you want to put up another PR.

Comment (EliottFlechtner) [reply src/multiharp/mhlib_wrapper/stub.rs]: I will just do it here. Changes including this were just pushed.

File: src/multiharp/mhlib_wrapper/stub.rs (hunk 5 above)
Comment (auspicacious) [reply src/multiharp/mhlib_wrapper/stub.rs]: My suggestion would be to [avoid using the resolve button](https://github.com/moonshot-nagayama-pj/public-documents/blob/main/engineering/git-workflow.md#address-review-comments). I've had a lot of issues from people overconfidently marking things resolved before the reviewer actually looks at them.

File: src/multiharp/mhlib_wrapper/stub.rs [hunk 10]
```diff
@@ -1,20 +1,37 @@
...
 };
 
-#[derive(PartialEq, Clone, Debug)]
+/// A stub implementation of the `MhlibWrapper` trait for testing purposes.
+/// It simulates the behavior of the real MHLib wrapper without requiring
+/// actual hardware interaction.
+#[derive(Debug)]
 pub struct MhlibWrapperStub {
     device_index: u8,
+    measurement_end: Mutex<Option<Instant>>,
```
Comment (auspicacious) [inline src/multiharp/mhlib_wrapper/stub.rs:18]: Is the mutex doing anything useful now, or can we just replace this with `Option<Instant>`?

File: src/multiharp/mhlib_wrapper/stub.rs [hunk 11]
```diff
@@ -222,11 +242,12 @@ impl MhlibWrapper for MhlibWrapperStub {
     }
 
     fn read_fifo(&self) -> Result<Vec<u32>> {
```
Comment (auspicacious) [inline src/multiharp/mhlib_wrapper/stub.rs:245]: Ok, I think you were a little overzealous in removing comments, the `read_fifo` one was usefully describing the behavior of this stub. It's not critical, though.

Comment (EliottFlechtner) [reply src/multiharp/mhlib_wrapper/stub.rs:245]: Fair point + fixed. I restored a shorter comment here that just describes the stub's observable behavior without the extra implementation detail.

File: src/multiharp/mhlib_wrapper/stub.rs (hunk 10 above)
Comment (EliottFlechtner) [reply src/multiharp/mhlib_wrapper/stub.rs:18]: I think the mutex is still doing useful work here. `start_measurement` and `stop_measurement` both mutate this state through `&self`, so we still need interior mutability, right ; a plain `Option<Instant>` would then not work with the current trait/method signatures I think? Since MhlibWrapper is also Send + Sync, Mutex<Option<Instant>> is the **minimal way to keep that mutable state in the stub** imo.

Comment (auspicacious) [reply src/multiharp/mhlib_wrapper/stub.rs:18]: Oof, I probably have a TODO somewhere in this project that says something like "Some of these things probably aren't actually `Sync`, but it seemed to be necessary, this needs to be fixed at some point." Did I mention this was my first major Rust project?

**Review by auspicacious — APPROVED** [review]

File: src/multiharp/mhlib_wrapper/stub.rs (hunk 10 above)
Comment (EliottFlechtner) [reply src/multiharp/mhlib_wrapper/stub.rs:18]: Mine too honestly, I'm learning Rust as we speak! I had to deal with a lot of thread behaviors in the past in C# or C++ but I have to admit Rust's typing is a bit of a mystery still... My previous explanations are out of various online sources I read about this. Thanks for approving the PR!

**Comment by EliottFlechtner** [comment]
Sorry for early close, I thought it had been merged already. I reopened it and will let you do it when done @auspicacious
